---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "payment.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "payment.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azureKeyVault.managedIdentityClientId | quote }}
    keyvaultName: {{ .Values.azureKeyVault.name | quote }}
    tenantId: {{ .Values.azureKeyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: {{ .Values.azureKeyVault.secrets.databaseConnection | default "Payment-DatabaseConnection" | quote }}
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.azureKeyVault.secrets.rabbitmqConnection | default "Payment-RabbitMQConnection" | quote }}
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.azureKeyVault.secrets.redisConnection | default "Payment-RedisConnection" | quote }}
          objectType: secret
          objectVersion: ""
  secretObjects:
    - secretName: {{ include "payment.fullname" . }}-secrets
      type: Opaque
      data:
        - objectName: {{ .Values.azureKeyVault.secrets.databaseConnection | default "Payment-DatabaseConnection" | quote }}
          key: database-connection
        - objectName: {{ .Values.azureKeyVault.secrets.rabbitmqConnection | default "Payment-RabbitMQConnection" | quote }}
          key: rabbitmq-connection
        - objectName: {{ .Values.azureKeyVault.secrets.redisConnection | default "Payment-RedisConnection" | quote }}
          key: redis-connection

