---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "notification.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notification.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azureKeyVault.managedIdentityClientId | quote }}
    keyvaultName: {{ .Values.azureKeyVault.name | quote }}
    tenantId: {{ .Values.azureKeyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: {{ .Values.azureKeyVault.secrets.rabbitmqConnection | default "Notification-RabbitMQConnection" | quote }}
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.azureKeyVault.secrets.smtpHost | default "Notification-SmtpHost" | quote }}
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.azureKeyVault.secrets.smtpPassword | default "Notification-SmtpPassword" | quote }}
          objectType: secret
          objectVersion: ""
  secretObjects:
    - secretName: {{ include "notification.fullname" . }}-secrets
      type: Opaque
      data:
        - objectName: {{ .Values.azureKeyVault.secrets.rabbitmqConnection | default "Notification-RabbitMQConnection" | quote }}
          key: rabbitmq-connection
        - objectName: {{ .Values.azureKeyVault.secrets.smtpHost | default "Notification-SmtpHost" | quote }}
          key: smtp-host
        - objectName: {{ .Values.azureKeyVault.secrets.smtpPassword | default "Notification-SmtpPassword" | quote }}
          key: smtp-password

