---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "payment.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "payment.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.azureKeyVault.managedIdentityClientId }}
    azure.workload.identity/client-id: {{ .Values.azureKeyVault.managedIdentityClientId | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}

