apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: identity-secrets
  namespace: platform
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""  # Set to your managed identity ID
    keyvaultName: ""  # Set to your Azure Key Vault name
    tenantId: ""  # Set to your Azure tenant ID
    objects: |
      array:
        - |
          objectName: Identity-DatabaseConnection
          objectType: secret
          objectVersion: ""
        - |
          objectName: Identity-RedisConnection
          objectType: secret
          objectVersion: ""
        - |
          objectName: Identity-JwtSecret
          objectType: secret
          objectVersion: ""
    secretObjects:
      - secretName: identity-secrets
        type: Opaque
        data:
          - objectName: Identity-DatabaseConnection
            key: database-connection
          - objectName: Identity-RedisConnection
            key: redis-connection
          - objectName: Identity-JwtSecret
            key: jwt-secret

