apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: platform
  labels:
    app: identity-api
spec:
  type: ClusterIP
  selector:
    app: identity-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  sessionAffinity: None

